schema_version = 0
kind = "core-binaries"
evo_core_tag = "v0.1.9"
target = "armv7-unknown-linux-gnueabihf"
binaries = ["evo", "evo-plugin-tool"]
built_at = "2026-04-28T07:02:19Z"
publisher = "org.evoframework"
